" Vim defaults
" These are sorted by 'category'
" Basic Terminal
        set clipboard+=unnamedplus
        set ttyfast     
        set lazyredraw  
        set mouse=a     
        set ttymouse=xterm2
        set term=screen-256color
        set t_Co=256    
        set background=dark
        set shell=dash
" UTF8 is my system default encoding.
        set nocompatible 
        set encoding=utf8
        scriptencoding utf-8
" Tab Behaviour
        set tabstop=4
        set softtabstop=4
        set shiftwidth=4
        set autoindent
        set smartindent
        set expandtab
" Search Behaviour
        set magic
        set ignorecase
        set smartcase
        set hlsearch
        set incsearch
" Backups and Undo
        set nobackup
        set noswapfile
        set autochdir
        set autoread 
        set autowriteall
" LineFolding
        set foldenable
        set foldmethod=indent
        set foldlevel=1

        set wrap
        set whichwrap+=b,s,h,l,<,>,[,]
        set backspace=indent,eol,start
" WildMenu
        set wildmenu
        set wildmode=list:longest,full
        set wildignore=*.o,*.git,*.a,*.so,*.pyc
        set showcmd
        set showmode
" Line Numbers on Steroids
        set number
        set ruler
        " set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
        set cursorline  
        set colorcolumn=80
        set scrolljump=6
        set scrolloff=6
        set pastetoggle=<F9>
        set laststatus=2
        let history=2048

""""""""""""""""""""""""""""""""
" Mappings
"+++++++++++++++++++++++++++++++
        let mapleader="-"
        let g:mapleader="-"

        nnoremap ; :
        nmap Y d$ 
        " Easy paste mode
        map <leader>pp :setlocal paste!<CR>
        " Easily Edit .vimrc
        nmap <silent> <leader>ve :e  ~/.vimrc<CR>
        nmap <silent> <leader>vs :so ~/.vimrc<CR>
        " au BufWritePost .vimrc so ~/.vimrc
        " Easy Undo
        nnoremap <leader>u <esc>u
        nnoremap <leader>r <C-r> 
        " Easy Ctrl-z
        nnoremap <leader>d <C-z>
        " Easy split window.
        nnoremap <leader>- <esc>:split<CR>
        nnoremap <leader>= <esc>:vsplit<CR>

        "cmap w!! %!sudo tee >> /dev/null %

""""""""""""""""""""""""""""""""
" Vundle
"+++++++++++++++++++++++++++++++
        set rtp+=~/.vim/bundle/vundle/
        set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim/
        filetype on
        filetype off
        call vundle#rc()
        " Vundle
        Bundle 'gmarik/vundle'
        Bundle 'gmarik/github-search.vim'
        " ColorSchemes
        " My Favorite!!
        Bundle 'molokai'
        Bundle 'vim-scripts/xterm-color-table.vim'
        Bundle 'godlygeek/csapprox'
        Bundle 'tpope/vim-colors-solarized'
        Bundle 'spf13/vim-colors'  
        Bundle 'flazz/vim-colorschemes'
        " Utilities
        Bundle 'tpope/vim-fugitive'
        Bundle 'tpope/vim-markdown'
        Bundle 'Lokaltog/vim-powerline'
        Bundle 'scrooloose/nerdtree'
        Bundle 'scrooloose/nerdcommenter'
        Bundle 'scrooloose/syntastic' 
        Bundle 'vim-scripts/license-loader'
        Bundle 'vim-scripts/gnupg-symmetric.vim'
        Bundle 'ervandew/supertab'
        Bundle 'JesseKPhillips/d.vim'
        filetype plugin indent on

syntax on
"colorscheme molokai 
" Solarized
let g:solarized_menu=0
let g:solarized_termcolors=256
let g:solarized_italic=0
let g:solarized_underline=1
let g:solarized_termtrans=0
colorscheme solarized
